requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "task1"
readme = "README.md"
requires-python = ">=3.9"
version = "0.0.1"
dependencies = [
  "fastapi",
  "motor",
]
[tool.setuptools.packages.find]
where = ["src"]